### ISSUE TITLE
Can the RANS  be solved with this? What changes should be made to the network

### ISSUE THREAD

**Issue by LiChengChen666** [yellowshippo/penn-neurips2022#2]
Different differential equations are going to have different structures, but is it okay to use the same structure.

**Comment by yellowshippo** [comment]
@LiChengChen666 

Yes, you can use the same structure for both DNS and RANS. Or, you can also refine the architecture to be more suitable for RANS. To do so, 1) you can define the governing equation you would like to solve (e.g., equations for RANS), 2) write the encoded version using NIsoGCN as done in the paper (e.g., Equations 58-61), and 3) implement it. Step 2 seems complicated at first glance, but actually, it is straightforward because all you need is to replace spacial gradient operators with corresponding NIsoGCN layers.
<img width="816" alt="Screenshot 2023-04-21 at 22 46 48" src="https://user-images.githubusercontent.com/1397421/233652352-f7669233-45ef-4012-995d-f8dbb5d264e8.png">

Our method can deal with any partial differential equation, as we demonstrated the Navier–Stokes equations and advection-diffusion equation (see Appendix C and D in the paper).

Hope this helps!

**Comment by LiChengChen666** [comment]
Thank you very much. I have a new question. 
If I have a mesh consists of ca. 30 million vertices and I want to preserve geometric features, what should I do？

**Comment by yellowshippo** [comment]
First, you can just preprocess your mesh and try to learn it. If you encounter an out-of-memory error, consider these options:

* Model size reduction: Specifically, decrease the number of neurons and/or iterations in the neural nonlinear solver.
* Model parallelism: Divide the model to take advantage of multi-GPU capabilities (cf. https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html )
* Mesh partitioning: Like model parallelism, you can use multi-GPU by partitioning the mesh (cf. https://docs.dgl.ai/guide/distributed.html )

I'm also keen on learning large-scale meshes, so if you manage to learn your mesh successfully, please let me know. We can then discuss potential future directions together. Good luck!
